<a href="https://colab.research.google.com/github/iamslash/examplesofml/blob/master/tensorflow_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

In [3]:
n_a = np.arange(100)
n_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
print(type(n_a))

<class 'numpy.ndarray'>


In [5]:
n_a.shape

(100,)

In [0]:
t_a = tf.Variable(n_a)

In [7]:
t_a

<tf.Variable 'Variable:0' shape=(100,) dtype=int64_ref>

In [0]:
sess = tf.Session()

In [9]:
sess.run(tf.initialize_all_variables())

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [0]:
sess.run(tf.global_variables_initializer())

In [11]:
sess.run(t_a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
type(sess.run(t_a))

numpy.ndarray

In [13]:
sess.run(t_a).shape

(100,)

In [0]:
n_b = np.arange(20).reshape(4, 5)

In [15]:
n_b.shape

(4, 5)

In [16]:
n_c = n_b.reshape(2, 10)
n_c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [0]:
t_r = tf.reshape(n_b, [5, 4])

In [18]:
t_r

<tf.Tensor 'Reshape:0' shape=(5, 4) dtype=int64>

In [19]:
sess.run(t_r)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
t_r2 = tf.reshape(n_b, [1, 20])
t_r2
sess.run(t_r2)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [22]:
t_r3 = tf.reshape(n_b, [10, -1])
sess.run(t_r3)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [23]:
t_r4 = tf.reshape(n_b, [-1])
sess.run(t_r4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
value = tf.ones([5, 30])
split0, split1, split2 = tf.split(value, [4, 15, 11], 1)

In [30]:
split0.shape

TensorShape([Dimension(5), Dimension(4)])

In [31]:
n_d = np.arange(9).reshape(3,3)
n_d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
t_d_0 = tf.expand_dims(n_d, 0)
sess.run(t_d_0)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [33]:
t_d_0.shape

TensorShape([Dimension(1), Dimension(3), Dimension(3)])

In [0]:
t = tf.squeeze(t_d_0)

In [35]:
t


<tf.Tensor 'Squeeze:0' shape=(3, 3) dtype=int64>

In [36]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
list_n = [x, y, z]
t_p = tf.pack(list_n)
sess.run(t_p)

AttributeError: ignored